### PR TITLE
Made changes to the theme, fixed UI issue

### PR DESCRIPTION
**Pull request by vaibhav-1508**
Made the necessary changes as mentioned here: https://github.com/Sanket1308/Simple-Calculator/pull/59#issuecomment-1267950410 @Sanket1308

### CODE REVIEW

**Comment by vaibhav-1508** [comment]
@Sanket1308 ?

**Comment by vaibhav-1508** [comment]
@Sanket1308 🫥🫠🥲

**Comment by boradesanket13** [comment]
This branch has conflicts that must be resolved!

**Comment by vaibhav-1508** [comment]
> This branch has conflicts that must be resolved!

commits resolved

**Comment by vaibhav-1508** [comment]
@Sanket1308 was there some issue with the PR?

**Comment by boradesanket13** [comment]
This branch has conflicts that must be resolved!

**Pull request closed without merging**
