### PR TITLE
Neumorphism ui created

### PR DESCRIPTION
**Pull request by Tushar98644**
Screenshot 2022-12-28 at 12 54 41 AM

### CODE REVIEW

**Comment by boradesanket13** [comment]
Keep the operators ( +, -, x, %) on right side
Fix calculators screen size
Screenshot (1221)

**Comment by boradesanket13** [comment]
@Will make this issue as HARD with 20 points

**Comment by boradesanket13** [comment]
@Tushar98644

**Comment by will** [comment]
> @will make this issue as HARD with 20 points

I refuse to make this issue HARD.

Instead, I make it SUPER EASY, but worth 1,000 points! I hope whoever does the issue can win first place because of the points.

**Pull request closed without merging**
